name: Pytest

on:
    pull_request:
        branches: ["master", "main"]

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3

            - name: Get pytest and other requirements
              run: |
                  sudo apt-get install python3
                  pip install -r $GITHUB_WORKSPACE/orodha-keycloak/test_requirements.txt
                  pip install pytest-cov

            - name: Run pytest
              run: pytest --cov $GITHUB_WORKSPACE/orodha-keycloak --cov-report xml:$GITHUB_WORKSPACE/coverage.xml

            - name: Get Coverage
              uses: orgoro/coverage@v3
              with:
                  coverageFile: coverage.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  thresholdAll: 0.8
